# Generated by Django 4.2.16 on 2024-10-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='headline',
            field=models.TextField(),
        ),
    ]
