# Generated by Django 4.2.16 on 2024-10-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('health_facility_name', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('facility_type', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('taluka_name', models.CharField(max_length=100)),
            ],
        ),
    ]
